In [7]:
from google.colab import drive
import os
import pickle

# Step 1: Mount Google Drive
drive.mount('/content/drive')

os.listdir('/content/drive/MyDrive/')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


['Classroom',
 'IMG_20210929_155246.jpg',
 'IMG_20220111_193821__01.jpg',
 'Rishab_3097_graph_theory.gdoc',
 'Cover letter Rishab Jaiswal BCS_AI_2B 211003003097.gdoc',
 'Getting_Started_with_Enterprise_grade_AI_Badge20240808-7-w8g6ey (2).pdf',
 'Getting_Started_with_Enterprise_grade_AI_Badge20240808-7-w8g6ey (1).pdf',
 'Artificial_Intelligence_Fundamentals_Badge20240810-8-r6g1uf (2).pdf',
 'Artificial_Intelligence_Fundamentals_Badge20240810-8-r6g1uf (1).pdf',
 'Getting_Started_with_Artificial_Intelligence_Badge20240810-8-qp5zu4 (2).pdf',
 'Getting_Started_with_Artificial_Intelligence_Badge20240810-8-qp5zu4 (1).pdf',
 'Getting_Started_With_Artificial_Intelligence_Badge.png',
 'image.png',
 'image (1).png',
 'Udemy_Numpy.pdf',
 'Internzvalley_Certificate_of_training.pdf',
 'Internzvalley_Certificate_of_Internship.pdf',
 'Getting_Started_with_Enterprise_grade_AI_Badge20240808-7-w8g6ey.pdf',
 'Getting_Started_with_Artificial_Intelligence_Badge20240810-8-qp5zu4.pdf',
 'CIT.pdf',
 'Artificia

In [8]:
os.listdir('/content/drive/MyDrive/Colab Notebooks/')

['placement_prediction.ipynb',
 'Importing data from API.ipynb',
 'EDA-univariate-analysis.ipynb',
 'EDA-Bivariate-Multivariate-Analysis.ipynb',
 'EDA_Automation.ipynb',
 'Feature_Scaling_Standardization.ipynb',
 'Normalization.ipynb',
 'Encoding Categorical Data.ipynb',
 'Encoding_Categorical_Data_2.ipynb',
 'Column_Encoding.ipynb',
 'Pipeline_1.ipynb',
 'Predict_Tinatic_without_Pipeline.ipynb',
 'Untitled',
 'models']

In [9]:
os.listdir('/content/drive/MyDrive/Colab Notebooks/models/')

['ohe__embarked.pkl', 'clf.pkl', 'ohe__sex.pkl']

In [13]:
os.chdir('/content/drive/MyDrive/Colab Notebooks/models/')

**importing the files from model folder**

In [15]:
with open('ohe__sex.pkl','rb') as file:
  ohe_sex = pickle.load(file)

In [16]:
with open('ohe__embarked.pkl','rb') as file:
  ohe_embarked = pickle.load(file)

In [18]:
with open('clf.pkl','rb') as file:
  clf = pickle.load(file)

# Creating a new test data to test that our model is working or not.

In [23]:
# test_input
import numpy as np
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype = object).reshape(1,7)

In [24]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

**Preprocessing the new test data as we hav dobe with x_train and then concatetating all together and in order.**

In [25]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0, 1]], dtype=int32)

In [26]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

array([[0, 0, 1]], dtype=int32)

In [28]:
test_input_age = test_input[:,2].reshape(1,1)

In [29]:
test_input_transform = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked), axis=1)

In [30]:
test_input_transform.shape

(1, 10)

**now pass the preprocessed data to get the prediction.**

In [31]:
clf.predict(test_input_transform)

array([0])