PCA aims to scale down the higher dimensional data to a lower dimensional data keeping the essance of the data.

It takes the smallest possible dimension.

It results in faster execution of algo and it helps to visualize a higher dimensional data as it converts the whole data in a lower dimensional as 3D or 2D, because these two can only be observed by humans not more than this.

For a non known data set if we have to select some features of the data for our model then plot scatter plot of two columns and see data spread is more for which feature.

eg: we have three columns as **No. of Room**, **No. of Grocery shop**, **Price** i have to select some of the features out of these three.

for this i will plot scatter plot for **room** and **grocery** and will observe where the data spread is more.

the feature the most data spread is taken and the other is removed.

If the data set has **No of Room**, **No of washrooms**, **Price** then here we cant do feature selection as spread of both the feature on both the axis is almost comparable to each other

Therefore we will apply feature extraction --> Creating a new feature as **size of the flat** now here this feature is equivalent to **no of room** and **no of washroom**

Variance is used for PCA.

Number of input column is = num of dimension.

**step 1:** mean centering with respect to every axis(dimension).

**step 2:** Find the co variance matrix
The matrix will be dimension x dimension
**eg:** we have f1, f2, f3 as the input columns then.

v(f1)      c(f2.f1)   c(f1.f3)

c(f1.f2)   v(f2)      c(f2.f3)

c(f1.f3)   c(f2.f3)   v(f3)

**step 3:** Find the eigen value and eigen vector for the co variance matrix.

For the above example we will get a set of 3 eigen values and a set of 3 eigen vectors say X1, X2, X3 and in this set of 3 vectors the vector which has the highest eigen value that is refered as PC1 then PC2 and then PC3.

Now if we consider only PC1 then dimension is reduced to 1D, if PC1 and PC2 is considered then dimension is reduced to 2D.

In [4]:
import numpy as np
import pandas as pd

np.random.seed(23)

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = pd.concat([df, df1], ignore_index=True)
df = df.sample(40)

In [6]:
df.head()

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [7]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [8]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [9]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [10]:
# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [11]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [12]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [13]:
pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [14]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0
2 -0.271876  0.498222       1
3 -0.621586  0.023110       1
4  1.567286  1.730967       1

In [15]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()